[build]
  command = "npm install -g npm@8 && npm config set legacy-peer-deps true && npm install --force --ignore-scripts && npm run build"
  publish = "build"

[context.production]
  [context.production.environment]
    REACT_APP_APP_ENV = "production"

[context.dev]
  [context.dev.environment]
    REACT_APP_APP_ENV = "staging"