[build]
  command = "npm install -g yarn && yarn cache clean && NODE_ENV=production yarn install --frozen-lockfile --network-timeout 100000 && yarn run build:unix"
  publish = "build"

[context.production]
  [context.production.environment]
    REACT_APP_APP_ENV = "production"

[context.dev]
  [context.dev.environment]
    REACT_APP_APP_ENV = "staging"