[build]
  command = "npm install --legacy-peer-deps --no-fund --no-audit --force && npm run build:unix"
  publish = "build"

[context.production]
  [context.production.environment]
    REACT_APP_APP_ENV = "production"

[context.dev]
  [context.dev.environment]
    REACT_APP_APP_ENV = "staging"