[build]
  command = "npm install -g npm@8 && npm install --force --legacy-peer-deps && npm run build"
  publish = "build"

[context.production]
  [context.production.environment]
    REACT_APP_APP_ENV = "production"

[context.dev]
  [context.dev.environment]
    REACT_APP_APP_ENV = "staging"