[build]
  command = "npm install -g npm@8 && npm cache clean --force && npm config set legacy-peer-deps true && npm install --no-fund --no-audit --prefer-offline --force && npm run build:unix"
  publish = "build"

[context.production]
  [context.production.environment]
    REACT_APP_APP_ENV = "production"

[context.dev]
  [context.dev.environment]
    REACT_APP_APP_ENV = "staging"